### ISSUE TITLE
inconsistent API results - possible sharding issue?

### ISSUE THREAD

**Issue by boblaublaw** [eegeo/eegeo-poi-api#3] opened 2018-10-23 21:35 UTC
We are noticing inconsistent query results when we query the POI API "tag" method.

I've used the following one liner to request the same data 15 times, just a few seconds apart:
```
x=1; while [ $x -lt 15 ] ;do
     curl "https://poi.wrld3d.com/v1.1/tag?t=${REDACTED}&r=250000000&lat=37.8083361&lon=-122.2661149&apikey=${REDACTED}" > $x.json ;
     sleep 1;
     x=$((x+1)); 
done
```
This creates 15 files named 1.json through 15.json.  Examining those results yields two groupings of slightly different results.  I'm hashing the result files here just to show which are the same:
```
[joe@prolepsis scripts(master) $]$ shasum ?.json ??.json | sort
4b7e744711cf1421256718f90482d74704bdc964  1.json
4b7e744711cf1421256718f90482d74704bdc964  11.json
4b7e744711cf1421256718f90482d74704bdc964  12.json
4b7e744711cf1421256718f90482d74704bdc964  13.json
4b7e744711cf1421256718f90482d74704bdc964  3.json
4b7e744711cf1421256718f90482d74704bdc964  5.json
4b7e744711cf1421256718f90482d74704bdc964  8.json
4b7e744711cf1421256718f90482d74704bdc964  9.json
90dce0f1a4d750cccbc5dfb012eed392f4efda4b  10.json
90dce0f1a4d750cccbc5dfb012eed392f4efda4b  14.json
90dce0f1a4d750cccbc5dfb012eed392f4efda4b  2.json
90dce0f1a4d750cccbc5dfb012eed392f4efda4b  4.json
90dce0f1a4d750cccbc5dfb012eed392f4efda4b  6.json
90dce0f1a4d750cccbc5dfb012eed392f4efda4b  7.json
```

You can see the results hash to either `90dce0f1a4d750cccbc5dfb012eed392f4efda4b` or `4b7e744711cf1421256718f90482d74704bdc964`.  

Is this a load balancer redirecting requests to a server that has lost sync?

**Comment by boblaublaw** [comment] 2018-10-23 21:42
Then again, upon examining the headers, the "Server" field always indicates "Cowboy".  In any case, this is unexpected behavior - please advise!

**Comment by boblaublaw** [comment] 2018-10-23 21:46
Digging a little further, I compared the id values of the POI from these two result sets, and they compare as follows:
```
[joe@prolepsis scripts(master) $]$ diff --side-by-side 0.ids 2.ids
                                                              >     "id": 158027,
                                                              >     "id": 158028,
                                                              >     "id": 158036,
                                                              >     "id": 158037,
                                                              >     "id": 158039,
                                                              >     "id": 282083,
                                                              >     "id": 282084,
                                                              >     "id": 282085,
    "id": 344691,                                                   "id": 344691,
    "id": 397395,                                                   "id": 397395,
    "id": 397396,                                                   "id": 397396,
    "id": 397399,                                                   "id": 397399,
    "id": 397400,                                                   "id": 397400,
    "id": 397402,                                                   "id": 397402,
    "id": 397403,                                                   "id": 397403,
    "id": 397404,                                                   "id": 397404,
    "id": 397405,                                                   "id": 397405,
    "id": 397407,                                                   "id": 397407,
    "id": 397452,                                                   "id": 397452,
    "id": 397453,                                                   "id": 397453,
    "id": 397460,                                             <
    "id": 397461,                                             <
    "id": 397463,                                             <
    "id": 397465,                                             <
    "id": 397466,                                             <
    "id": 397468,                                             <
    "id": 397469,                                             <
    "id": 158027,                                             <
```
The same number of results is returned both times, with about 2/3rds overlap in terms of which records are present.

**Comment by malcolm-brown** [comment] 2018-10-24 12:33
Thanks for the detailed report!

We've not been able to reproduce this exact case with internal POI sets, but one possibility is that we use the radius (r) parameter to filter and score the returned results so they're ordered from closest to furthest matching POIs.  Using an exceedingly high radius value (250000000m) may result in precision inaccuracies between search queries depending on the geographical distribution of the POIs.  This is likely a bug, as we're not clamping the radius value to a maximum limit for the scoring - If you get more consistent results with a smaller radius value, this is likely what the problem is.  We can implement a fix to clamp the radius to an accepted limit.

Additionally, the server header is returning an expected value and this is not unexpected behavior.

**Comment by MephestoKhaan** [comment] 2018-10-24 13:24
I tried the same with a sighly smaller radious of 250000m and the problem persists.
I would like to retrieve all POIs around the globe, is it not possible? What would be the max radious?

**Comment by boblaublaw** [comment] 2018-10-24 20:14
As @MephestoKhaan has pointed out (we are working together on this), we are doing a large radius search because our application initialization is using a small number (around 20 elements) of specially tagged POI to indicate "sites", which could be anywhere in the globe.  

Once our user selects a site, we constrain the radius value for subsequent searches to a much much more reasonable value (5000 meters).

If there is another way for us to perform this global tag search without a huge radius, please advise!

**Comment by malcolm-brown** [comment] 2018-10-25 10:43
Internally we treat anything higher than 6300000 as a "global" search, so we'd expect you to retrieve global results with any `r` value higher than that.  The only thing `r` affects after that is subtly weighting the results based on distance from the query lat/lon.

We've still not internally been able to reproduce this issue with a set of 15 POIs scattered across the globe, and instead get consistent sorted results each time.  Would it be possible to give us:

- A dummy set of POIs (mainly just lat/lons and a consistent tag) you've been able to reproduce the issue with.
- The exact curl command/web request used (Presuming it's the same one listed above?)

This should hopefully help us reproduce & narrow down the issue.

**Comment by boblaublaw** [comment] 2018-10-25 16:36
Happy to share this exact query with you but don't want to share an apikey publicly. Could you provide your WRLD email address to me at the following email address: joe at spatialfirst dot com.

**Comment by malcolm-brown** [comment] 2018-10-26 08:20
We probably don't need the specific apikey since we assume it's just a key that's been associated with your POI set. The important stuff for now is the specific POIs and the other parameters of your curl request if they differ from your initial request:

`https://poi.wrld3d.com/v1.1/tag?t=${REDACTED}&r=250000000&lat=37.8083361&lon=-122.2661149&apikey=${REDACTED}`

As for mailing us, best to just use support@wrld3d.com

**Comment by boblaublaw** [comment] 2018-10-26 18:30
Thanks, I've just now emailed the exact URL

**Comment by boblaublaw** [comment] 2018-10-28 22:58
Apologies, I've done a data cleanup without remembering that you may have not yet looked at this.  I'm afraid the query results are considerably smaller now, and may not even exhibit the issue.  I will retest and comment with results ASAP.

**Comment by malcolm-brown** [comment] 2018-10-31 12:46
Hi, we are still unable to reproduce this either with the API key + POI set access you provided, nor with our own internal POI sets.  You mentioned a data cleanup that might have affected it - are you still seeing this issue?

**Comment by boblaublaw** [comment] 2018-10-31 18:03
Yes, it appears the data cleanup did impact our ability to reproduce this - apologies for that.  If you were to close this, we would understand.  If we see other instances in the future we can return and reopen as needed.

**Comment by malcolm-brown** [comment] 2018-11-07 10:57
Closing this now then, as per discussion.  We'll keep an eye on this issue if it resurfaces.

**Closed as completed by malcolm-brown** 2018-11-07 10:57 UTC
